<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Bridges.PackGen</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bridges.Core\Bridges.Core.csproj" />
  </ItemGroup>

</Project>
